server:
port: ${PORT:8080}
address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://hopper.proxy.rlwy.net:12135/railway
    username: postgres
    password: yzUZHXEUVmJdPmEfjImzaoefoyRMloQo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: smtp.gmail.com
#    port: 465
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            trust: smtp.gmail.com
product:
  service:
    url: https://productservice.up.railway.app
